- name: simple pv vg and lv creation
  hosts: all
  tasks:
    - name: Create a physical volume on disks /dev/sdc
      community.general.parted:
        device: /dev/sdc
        number: 1
        flags: [ lvm ]
        state: present
        part_end: 100%
 
     - name: Create a volume group on disks /dev/sdb
       community.general.lvg:
         vg: datavg
         pvs: /dev/sdb1
         pesize: 16
 
     - name: Create a logical volume of 512m with disks /dev/sdb and /dev/sdc
       community.general.lvol:
           vg: datavg
           lv: datalv
           size: 100%
 
     - name: create a data dir
       ansible.builtin.shell: mkdir /data
 
     - name: Create a ext4 filesystem on /dev/sdb1
       community.general.filesystem:
         fstype: ext4
         dev: /dev/datavg/datalv
     - name: Mount up device by label
       ansible.posix.mount:
         path: /data
         src: /dev/datavg/datalv
         fstype: ext4
         state: present
          
