- name: create user on target machine
  hosts: all
  
  vars:

  tasks:
    - name: create user from the given variable list
      user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        append: true
        groups: wheel
        shell: /bin/bash
        state: present

      loop: "{{ users_list }}"
