- name: create user on target machine
  hosts: all
  
  vars:

  tasks:
    - name: create user from the given variable list
      user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        append: true
        groups: wheel
        shell: /bin/bash
        state: present
        expires: -1

      loop: "{{ users_list }}"

    - name: expire user password
      command: "passwd -e {{ item.name }}"

      loop: "{{ users_list }}"

