---
- name: Create LVM and mount points
  hosts: all
  become: yes

  tasks:
    - name: Create volume group
      lvm_vg:
        vg: "{{ item.lvm_vg }}"
        pvs: "{{ item.devices }}"
      loop: "{{ vg_list }}"

    - name: Create logical volumes
      lvm_lv:
        vg: "{{ item.0.lvm_vg }}"
        lv: "{{ item.1.lvm }}"
        size: "{{ item.1.lvm_size }}"
        state: present
      loop: "{{ vg_list | subelements('lvm_lv') }}"
      
    - name: Format the logical volumes
      filesystem:
        fstype: "{{ item.1.fs_type }}"
        dev: "/dev/{{ item.0.lvm_vg }}/{{ item.1.lvm }}"
      loop: "{{ vg_list | subelements('lvm_lv') }}"

    - name: Create mount points
      file:
        path: "{{ item.1.mount_point }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop: "{{ vg_list | subelements('lvm_lv') }}"

    - name: Mount the logical volumes
      mount:
        path: "{{ item.1.mount_point }}"
        src: "/dev/{{ item.0.lvm_vg }}/{{ item.1.lvm }}"
        fstype: "{{ item.1.fs_type }}"
        state: mounted
      loop: "{{ vg_list | subelements('lvm_lv') }}"