- name: Disable user mailbox from Exchange Server 2019
  hosts: all
  gather_facts: yes

  tasks:
    - name: Run create remote session command and disable exchange user
      ansible.windows.win_powershell:
        script: |

          #define remote username on exchange server
          $username = "{{ ansible_user }}"

          #define remote user password
          $password = "{{ ansible_password }}" | ConvertTo-SecureString -AsPlainText -Force

          #create user credential for remtote powershell excution
          $UserCredential = New-Object System.Management.Automation.PSCredential($username, $password)

          #create a session on one of exchange server
          $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri http://CBOHQ-MBX-01.coopbank.local/PowerShell/ -Authentication Kerberos -Credential $UserCredential

          #import powesheel session
          Import-PSSession $Session -DisableNameChecking

          #excute Disable mailbox user cmdlet
          Disable-Mailbox -Identity "{{ usename }}"  -Confirm:$false

          #remove remote session
          Remove-PSSession $Session

      become_method: runas
      become_user: Administrator
