- name: Disable user mailbox from Exchange Server 2019
  hosts: all
  gather_facts: yes

  tasks:
    - name: Run create remote session command and disable exchange user
      ansible.windows.win_powershell:
        script: |
          try {
              # Define remote username on exchange server
              $username = "{{ ansible_user }}"

              # Define remote user password
              $password = "{{ ansible_password }}" | ConvertTo-SecureString -AsPlainText -Force

              # Create user credential for remote powershell execution
              $UserCredential = New-Object System.Management.Automation.PSCredential($username, $password)

              # Create a session on one of the exchange servers
              $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri http://CBOHQ-MBX-01.coopbank.local/PowerShell/ -Authentication Kerberos -Credential $UserCredential

              # Import powershell session
              Import-PSSession $Session -DisableNameChecking

              # Execute Disable mailbox user cmdlet
              Disable-Mailbox -Identity "{{ username }}" -Confirm:$false

              # Remove remote session
              Remove-PSSession $Session

              # If execution was successful, return success message
              Write-Output "Mailbox for {{ username }} disabled successfully"
          }
          catch {
              # If there is an error, return the error message
              Write-Output "Error disabling mailbox for {{ username }}: $_"
              exit 1
          }
      become_method: runas
      become_user: Administrator
      register: result
      failed_when:
        - result.error | length > 0
        - "'Error disabling mailbox' in result.host_out"

    - name: Fail if disabling mailbox failed
      fail:
        msg: "Task failed: {{ result.host_out }} {{ result.host_err }}"
      when: result.error | length > 0
