---
- hosts: Microsoft_Exchange_Server
  gather_facts: no
  tasks:

    - name: Check if task has already succeeded on any host
      ansible.builtin.set_fact:
        task_succeeded: "{{ hostvars[item]['task_succeeded'] | default(false) }}"
      loop: "{{ groups['Microsoft_Exchange_Server'] }}"
      when: "'task_succeeded' in hostvars[item]"

    - name: Disable mailbox user
      ansible.windows.win_powershell:
        script: |
          try {
              # Define remote username on exchange server
              $username = "{{ ansible_user }}"

              # Define remote user password
              $password = "{{ ansible_password }}" | ConvertTo-SecureString -AsPlainText -Force

              # Create user credential for remote powershell execution
              $UserCredential = New-Object System.Management.Automation.PSCredential($username, $password)

              # Create a session on one of the exchange servers
              $Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri http://CBOHQ-MBX-01.coopbank.local/PowerShell/ -Authentication Kerberos -Credential $UserCredential

              # Import powershell session
              Import-PSSession $Session -DisableNameChecking

              # Execute Disable mailbox user cmdlet
              Disable-Mailbox -Identity "{{ username }}" -Confirm:$false

              # Remove remote session
              Remove-PSSession $Session

              # If execution was successful, return success message
              Write-Output "Mailbox for {{ username }} disabled successfully"
          }
          catch {
              # If there is an error, return the error message
              Write-Output "Error disabling mailbox for {{ username }}: $_"
              exit 1
          }
      become_method: runas
      become_user: Administrator
      register: result
      when: task_succeeded | default(false) == false
      ignore_errors: true

    - name: Set task_succeeded fact if the task was successful
      ansible.builtin.set_fact:
        task_succeeded: true
      when: result.error | length == 0

    - name: Fail if task fails on all hosts
      fail:
        msg: "Task failed on all hosts"
      when: task_succeeded | default(false) == false
      run_once: true
