- name: Create user on different Linux and Win os
  hosts: all
  tasks:
    - name: Create user on Ubuntu/Debian
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/bash
        state: present
        create_home: yes
      when: ansible_facts.os_family == "Debian"

    - name: Create user on Fedora
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /bin/bash
        state: present
        create_home: yes
      when: ansible_facts.distribution == "Fedora"
    
    - name: Create a user on Windows Server
      ansible.windows.win_user:
        name: bob
        password: Coop#54321
        state: present
        groups:
        - Users
        - Administrators
      when: ansible_facts['os_family'] == "Windows"
    - name: Add user to sudoers (Ubuntu/Debian)
      ansible.builtin.user:
        name: "{{ username }}"
        groups: sudo
        append: yes
      when: ansible_facts.os_family == "Debian"
    

    - name: Add user to sudoers (CentOS/RHEL/Fedora)
      ansible.builtin.user:
        name: "{{ username }}"
        groups: wheel
        append: yes
      when: ansible_facts.os_family in ["RedHat", "Fedora"]
    
    - name: Set a password for the user
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
      when: username is defined and password is defined
  
