- name: create user on target machine
  hosts: all

  tasks:
    - name: create sudoer user on Redhat os
      user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        append: true
        groups: wheel
        shell: /bin/bash
        state: present
        expires: -1
      
      when: ansible_facts['os_family'] == "RedHat"
      loop: "{{ users_list }}"
    - name: create sudoer user on debian based os
      user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        append: true
        groups: sudo
        shell: /bin/bash
        state: present
        expires: -1
      
      when: ansible_facts['os_family'] == "RedHat"

      loop: "{{ users_list }}"

    - name: expire user password
      command: "passwd -e {{ item.name }}"

      loop: "{{ users_list }}"

