- name: Vmware create VM playbook
  hosts: localhost
  connection: local 
  gather_facts: yes
  tasks:
    - name: create Virtual Machine on Vcenter Server
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "{{ dc_name }}"
        folder: "{{ folder_name }}"
        name: "{{ vm_name }}"
        state: poweredon
        template: "{{ template_name }}"
        datastore: "{{ datastore }}"
        esxi_hostname: "{{ esxi_hostname }}"
        hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ vcpu }}"
          num_cpu_cores_per_socket: "{{ vcpu_per_socket }}"
          scsi: paravirtual
          hotadd_cpu: True
          hotremove_cpu: True
          hotadd_memory: True
          version: latest # Hardware version of virtual machine
          boot_firmware: "efi"
        networks:
          - name:  "{{ port_group }}"
            ip: "{{ ip_address }}"
            netmask: "{{ subnet_mask }}"
            gateway: "{{ network_gateway }}"
            connected: true
            device_type: vmxnet3
            start_connected: true
        wait_for_ip_address: true
        customization:
          dns_servers:
            - 8.8.8.8
            - 4.2.2.2
          script_text: |
            #!/bin/bash
            touch /tmp/touch-from-playbook

